config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :comments
  devise_for :users
  resources :posts do
    member do
      patch :hide
    end
    resources :comments, only: [ :create, :destroy ]
  end
  root to: "posts#index"
  resources :users
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments

  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :content, presence: true, length: { minimum: 5, maximum: 500 }
  scope :filter_by_category, ->(category_id) { where(category_id: category_id) if category_id.present? }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    if params[:category_id].present?
      @posts = Post.where(category_id: params[:category_id]).includes(:category).order(created_at: :desc)
    else
      @posts = Post.all.includes(:category).order(created_at: :desc)
    end
    @category = Category.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.user = current_user
    @category = Category.all
  end

  # GET /posts/1/edit
  def edit
  end

  def hide
    @post = Post.find(params[:id])

    @post.update(status: false)
    redirect_to posts_path
  end
  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @category = Category.find(params[:post][:category_id])
    @post.category = @category

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :status, :category_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
 <h3>Deja tu comentario:</h3>
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  <div class="field">
    <%= form.label :content, 'Tu comentario' %><br />
    <%= form.text_area :content, rows: 3 %>
  </div>

  <div class="actions">
    <%= form.submit 'Comentar' %>
  </div>
<% end %>

app/views/posts/_filterbycategory.html.erb
<%= form_with(url: posts_path, method: :get, local: true) do |form| %>
  <div>
    <%= form.label :category_id, "Filter by Category" %>
    <%= form.select :category_id, options_for_select(@category.collect { |category| [category.title, category.id] }, params[:category_id]), { include_blank: "All Categories" }, { class: "form-control" } %>
  </div>

  <div>
    <%= form.submit "Filter", class: "btn btn-primary" %>
  </div>
<% end %>

<div class="posts-list">
  <h1>Posts</h1>
  <% @posts.each do |post| %>
    <div class="post">
      <h2><%= post.title %></h2>
      <p><%= post.content %></p>
      <p><strong>Category:</strong> <%= post.category.title %></p>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, url: posts_path) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>
 <div>
    <%= form.label :category_id, "Category", style: "display: block" %>
     <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :title, @post.category_id), {}, class: "form-control" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">

  <% if post.status != false %>
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= post.category.title %>
  </p>
  <p>
    <strong>Created by:</strong>
    <%= post.user.email %>
  </p>

  <% end %>
 
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

 <% if current_user %>
  <p style="color: green">Hello <%= current_user.role%></p>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
  <%= link_to "Create Post", new_post_path %>

<% if current_user.role == "admin" %>
  <%= link_to "Create Category", new_category_path %>
  <% @category.each do |category| %>
    <%= render category %>
    <%= link_to "Show this category", category %>
  <% end %>
<% end %>

<div id="posts">
  <%= render "filterbycategory"  %>
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>
<% else %>
  <p>Please <%= link_to "log in", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %> to view posts.</p>
<% end %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="color: green"> Posts </h1>
<%= render @post %>


<% if current_user.id == @post.user.id %>
<div>

</div>
<% end %>
 <%= link_to "Back to posts", posts_path %>

 <%= render 'comments' %>
<% if current_user.role == "admin" %>
    <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= button_to "Destroy this post", @post, method: :delete %>
  <% end %>
<div>
  
   <%= render @post.comments.build %>
  <strong>Comments:</strong>
<% @comments.each do |comment| %>
  <p>
    <% if comment.user == nil  %> 
      <strong style="display: none">Anonymous</strong>
      <%= comment.content %>
    <% else %>
    <strong style="color: green"><%= comment.user.email %></strong>
    <%= comment.content %>
    <% end %>
    <% if current_user.role == "admin" && comment.content != nil %> 
      <%= button_to "Destroy this comment", comment, method: :delete %>
      <% end %>
  </p>
  </div>
<% end %>
</div>